spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled=true
      mvc:
        routes:
          - id: book-service
            uri:
              lb://book-service
            predicates:
              - Path=/v1/book/**
          - id: library-service
            uri:
              lb://library-service
            predicates:
              - Path=/v1/library/**


server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true

  instance:
    prefer-ip-address: true

#Actuator ayarları
management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0



